Repository vlv3k/Signal-App, pull requests merged in 2023-10, with the labels that each got.

#4 CSS Linking and fixed icons
  signal.html
Labels: bug, hacktoberfest-accepted, hacktoberfest

#6 Fixed : Speak Freely #2
  style.css
Labels: bug, good first issue, hacktoberfest-accepted, hacktoberfest

#7 Fixed : Button [Get Signal] Margin Problem
  signal.html
  style.css
Labels: bug, good first issue, hacktoberfest-accepted, hacktoberfest

#9 Added : Add Button Hover Effect
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, Future

#10 Changes simple desc
  Signal App Design
Labels: hacktoberfest-accepted, hacktoberfest, Future

#17 Added hero image
  img/sig-ss.png
  signal.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, Feature

#19 Fixed : Added Help Section and Footer Section
  signal
  signal.html
Labels: hacktoberfest-accepted, hacktoberfest, Feature
